---
kind: pipeline
type: docker
name: sysrootbuilder

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: embeddedreality/sysrooter
      username:
        from_secret: repo_username
      password:
        from:secret: repo_password

trigger:
  branch:
    - master
    
